name: Build&Test
on: workflow_dispatch
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Repo
            uses: actions/checkout@v4
        -   name: Installation Of Java
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'maven'
        # -   name: Compile
        #     run: mvn compile
        -   name: test
            run: mvn test
        # -   name: Package
        #     run: mvn clean package

        -   name: Setting DOCKER
            uses: docker/setup-buildx-action@v3
# ADD Credentials at settings, Under security there is Secrets & Variables
        -   name: Setting up Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD}}

        -   name: Build and push
            uses: docker/build-push-action@v6
            with: 
                    push: true
                    tags: twitter-app:latest